---
# tasks file for vagrant
- name: Install packages
  pacman:
    name: [vagrant, nfs-utils]
    state: present
    update_cache: yes
  become: yes

- name: Install vagran-libvirt and vagrant-reload plugin
  command: VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-libvirt vagrant-reload
  args:
    creates: '{{ ansible_user_dir }}/.vagrant.d/plugins.json'

- name: Add archlinux box
  command: vagrant box add files/package.box --name archlinux
  args:
    creates: '{{ ansible_user_dir }}/.vagrant.d/boxes/archlinux/0/libvirt/box.img'

# - name: Create folder
# - name: Create VagrantFile
