---
# tasks file for libvirt
- name: Install packages
  pacman:
    name: [virt-manager, edk2-ovmf, dnsmasq, ebtables]
    state: present
    update_cache: yes
  become: yes

- name: Add user to group libvirt
  user:
    name: '{{ ansible_user_id }}'
    groups: libvirt
    append: yes
  become: yes

- name: Start libvirt service
  systemd:
    name: libvirtd
    enabled: yes
    state: started
  become: yes

- name: Start virtlogd service
  systemd:
    name: virtlogd
    state: started
  become: yes
