---
# tasks file for libvirt
- name: Install packages
  pacman:
    name: [virt-manager, ovmf]
    state: present
    update_cache: yes
  become: yes
#- name: Install virt-manager
#
#
#- name: Add nvram qemu.conf
#- name: Change user for qemu.conf
#
#- name: Add user in libvirt group
#
#
#
#
#- name: Startd libvirt