---
- name: Install archiso
  pacman:
    name: archiso
    state: present
    update_cache: yes
  become: yes

- name: Create build folder
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ archiso_dir }}/archlive/airootfs/etc/systemd/system/dhcpcd@.service.d"
  become: yes

- name: Copy releng profile
  synchronize:
    src: "/usr/share/archiso/configs/releng/"
    dest: "{{ archiso_dir }}/archlive"
  become: yes

- name: Add ansible & git package
  lineinfile:
    path: "{{ archiso_dir }}/archlive/packages.x86_64"
    insertbefore: BOF
    state: present
    line: "{{ item }}"
  become: yes
  loop:
    - ansible
    - git

- name: Git clone koaxiel
  git:
    depth: 1
    repo: "https://github.com/Koaxiel/koaxiel.git"
    dest: "{{ archiso_dir }}/archlive/airootfs/root/koaxiel/"

- name: Permit ssh with empty password
  lineinfile:
    path: "{{ archiso_dir }}/archlive/airootfs/etc/ssh/sshd_config"
    insertafter: '#PermitEmptyPasswords no'
    line: PermitEmptyPasswords yes
  become: yes

- name: Install locale config
  copy:
    src: 'files/{{ item }}'
    dest: '{{ archiso_dir }}/archlive/airootfs/etc/{{ item }}'
  become: yes
  loop:
    - locale.conf
    - vconsole.conf

- name: Add mirrolist
  get_url:
    url: 'https://www.archlinux.org/mirrorlist/?country=FR&protocol=http&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on'
    dest: '{{ archiso_dir }}/archlive/airootfs/etc/pacman.d/mirrorlist'

- name: Add wpa_supplicant-wired.conf in root folder
  copy:
    src: files/wpa_supplicant-wired.conf
    dest: "{{ archiso_dir }}/archlive/airootfs/root/wpa_supplicant-wired.conf"
  become: yes

- name: Build iso
  command: "mkarchiso -v -w {{ archiso_dir }}/archlive/work -o {{ archiso_dir }} {{ archiso_dir }}/archlive"
  become: yes

- name: Copy image to libvirt storage
  copy:
    src: '{{ item }}'
    dest: '/var/lib/libvirt/images/archlinux.iso'
  with_fileglob: '*.iso'
  become: yes
